// ui/src/App.vue
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
import Navbar from '@/components/Navbar.vue'
import {ref,onMounted} from 'vue'
const dateTime = ref<string>('')

onMounted(()=>{
  setInterval(()=>{
    dateTime.value = new Date().toLocaleString('es-co')
  },1000)
})
</script>

<template>
 


  <Navbar :dateTime="dateTime"/>
  <div class="row justify-content-md-center">
    <div class="col col-lg-10">
      <div class="card">
        <div class="card-header">Stocket <i class="bi bi-archive-fill"></i></div>
        <div class="card-body">
          <RouterView />
        </div>
      </div>
    </div>
  </div>
</template>

// client/src/App.jsx
import { Outlet } from "react-router-dom";
import Navbar from "./components/Navbar";
import {useEffect, useState} from "react";

const App = () => {
    const [dateTime,setDateTime] = useState('');
    useEffect(() => {
        const interval = setInterval(() => {
            setDateTime(new Date().toLocaleString());
        },1000);
        return () => clearInterval(interval);
    }, []);
  return (
    <div>
      <Navbar dateTime={dateTime}/>
      <div className="row justify-content-lg-center mt-2">
        <Outlet />
      </div>
    </div>
  );
};

export default App;
