// ui/src/views/Auth/components/ChangePasswordComponent.vue
<template>
  <h4 class="card-title">
    Reestablecer Contraseña
  </h4>
  <!---Animacion de carga-->
  <div v-if="loading">
    <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75"
         aria-valuemin="0" aria-valuemax="100">
      <div class="progress-bar progress-bar-striped progress-bar-animated" :style="{ width: progress + '%' }">
      </div>
    </div>
  </div>
  <!----Fin animacion de carga-->
  <div v-else>
    <div v-if="sesion.isLogged">
      <p class="card-text">
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>¡Advertencia!</strong> Para cambiar su contraseña, haga clic en el botón de abajo. Se enviará un
          correo electrónico a su dirección de correo electrónico asociado al perfil con un enlace para cambiar su
          contraseña.
        </div>
        <button class="btn btn-warning" @click="sendEmail">Entendido, proceder</button>
      </p>
    </div>

    <div v-else>
      <p class="card-text">
        Para actualizar su contraseña, ingrese su correo electrónico y le enviaremos un enlace de reestablecimiento.
      </p>
      <form @submit.prevent="sendEmail">
        <div class="input-group mb-3">
          <span class="input-group-text" id="inputEmail"><i class="bi bi-envelope"></i></span>
          <input type="text" class="form-control" placeholder="Ingrese su correo electrónico" aria-label="Username"
                 aria-describedby="inputEmail" v-model="email" required/>
        </div>
        <button type="submit" class="btn btn-success" :disabled="!email || loading">Enviar correo</button>
      </form>
    </div>


  </div>

</template>
<script setup lang="ts">
import {ref} from 'vue'
import {resetPassword} from '../services/auth.apis';
import Swal from 'sweetalert2';
import {errorValidator} from '@/hooks/errors.hooks';
import {sesionStore} from '@/stores/sesion.store';
import {useRouter} from "vue-router";

const loading = ref<boolean>(false)
const sesion = sesionStore()
const email = ref<string>('')
const progress = ref<number>(0)
const url = useRouter()
const sendEmail = async () => {
  loading.value = true
  progress.value = 25
  const data = {
    ...(sesion.isLogged ? {email: sesion.UserData[0]?.email} : {email: email.value})
  }
  progress.value = 50
  await resetPassword(data)
      .then((Response) => {
        Swal.fire({
          icon: 'info',
          title: 'Correo Enviado',
          text: 'Se ha enviado un correo electronico a su direccion asociada, siga las instrucciones',
        })
        sesion.isLogged ? url.push({name: 'profile'}) : url.push({name: 'login'})
      })
      .catch((error) => {
        progress.value = 75
        const reciever = errorValidator(error.response.data)
        Swal.fire({
          icon: 'error',
          title: 'Error',
          text: reciever,
        })
      })
      .finally(() => {
        loading.value = false
        progress.value = 0
      })
}
</script>

// client/src/views/Auth/components/ChangePassword.jsx
import { useState } from "react";
import { IconHelperWitoutColors } from "../../../helpers/IconHelper";
import Loading from "../../../components/Loading";
import { errorMessage, successMessage } from "../../../components/messages";
import { useNavigate } from "react-router-dom";
import { actualizarContraseña } from "../services/auth.apis";
import useSesionStore from "../../../store/sesion.store";
const ChangePassword = () => {
  document.title = "Recuperar contraseña - Stocket";
  const [loading, setLoading] = useState(false);
  const { isAuth, userData } = useSesionStore.getState();
  const [data, setData] = useState({
    email: userData?.email || "",
  });
  const navigate = useNavigate();
  const handleChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
  };
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    await actualizarContraseña(data)
      .then((Response) => {
        successMessage(
          "¡Hecho!",
          "Se ha enviado un correo electrónico con instrucciones para reestablecer su contraseña."
        );
        navigate("/login");
      })
      .catch((error) => {
        errorMessage(error.response.data);
      })
      .finally(() => {
        setLoading(false);
      });
  };
  return (
    <div>
      <div className="card-header">
        <h3 className="card-title">Recuperar contraseña</h3>
      </div>
      <div className="card-body">
        <h5>Recuperar contraseña</h5>
        {loading ? (
          <Loading />
        ) : (
          <>
            <div className="row">
              <IconHelperWitoutColors
                url={"https://cdn.lordicon.com/nqisoomz.json"}
              />
              <div className="col">
                {isAuth && userData?.email ? (
                  <>
                    <p>
                      Se enviará un correo electrónico al correo asociado a su
                      cuenta. Para proceder, haga clic{" "}
                      <button
                        className="btn btn-success"
                        onClick={handleSubmit}
                      >
                        Aquí <i className="ri-chat-forward-line"></i>
                      </button>
                    </p>
                  </>
                ) : (
                  <>
                    <form className="form-horizontal" onSubmit={handleSubmit}>
                      <p>
                        Ingrese el correo electrónico asociado a su cuenta, y se
                        le enviará un mensaje con instrucciones para
                        reestablecer su contraseña.
                      </p>
                      <div className="card-body">
                        <div className="form-group">
                          {/*Correo */}
                          <label htmlFor="Username">
                            Correo electrónico{" "}
                            <i className="ri-account-box-line"></i>
                          </label>
                          <input
                            type="text"
                            className="form-control form-control-border border-width-2"
                            id="Username"
                            placeholder="Ingrese correo electrónico. Ej: correo@mail.com"
                            name="email"
                            onChange={handleChange}
                            required
                          />
                        </div>
                      </div>
                      <div className="container">
                        <div className="btn-group">
                          <button type="submit" className="btn btn-success">
                            Enviar <i className="ri-mail-send-fill"></i>
                          </button>
                        </div>
                      </div>
                    </form>
                  </>
                )}
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default ChangePassword;
