// client/src/views/Auth/components/Login.vue
<script setup lang="ts">
import Animations from '@/components/Animations.vue';
import Fingerprint from '@/assets/Icons/Fingerprint.json'
import useSesionStore from '@/stores/sesion.store';
import { ref } from 'vue'
import type { Login } from '../services/auth.interfaces';

document.title = 'Iniciar sesión - Stocket'


const sesion = useSesionStore()

const data = ref({} as Login)

const handleChange = (e: any) => {
  data.value = {
    ...data.value,
    [e.target.name]: e.target.value
  }
}

const handleSubmit = (e: any) => {
  e.preventDefault()
  sesion.iniciarSesion(data.value)
}
</script>
<template>
  <div class="card-header">
    <h6>Inicar sesión</h6>
  </div>
  <div class="card-body">
    <div class="row">
      <Animations :animation-data="Fingerprint" :style="{
        width: '100px',
        height: '100px'
      }" />
      <div class="col">
        <div class="card-title">
          <h5>Iniciar sesión</h5>
        </div>
        <p class="card-text">Ingrese sus credenciales para empezar</p>
        <form @submit="handleSubmit">
          <div class="input-group mb-3">
            <span class="input-group-text"><i class="bi bi-person-badge"></i></span>
            <div class="form-floating">
              <input type="text" name="username" @input="handleChange" class="form-control" id="Username"
                placeholder="Username">
              <label for="Username">Usuario</label>
            </div>
          </div>
          <div class="input-group mb-3">
            <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
            <div class="form-floating">
              <input type="password" name="password" @input="handleChange" class="form-control" id="Password"
                placeholder="Username">
              <label for="Password">Contraseña</label>
            </div>
          </div>
          <div class="btn-group">
            <button type="submit" class="btn btn-success">Entrar <i class="bi bi-arrow-right"></i></button>
            <button type="button" class="btn btn-secondary">¿Olvidó su contraseña?<i class="bi bi-question"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

// client/src/views/Auth/components/Login.jsx
import { useState } from "react";
import Loading from "../../../components/Loading";
import { obtenerTokens } from "../services/auth.apis";
import { successMessage, errorMessage } from "../../../components/messages";
import useSesionStore from "../../../store/sesion.store";
import { useNavigate, Link } from "react-router-dom";
import { RedirectIfIsAuth } from "../../../hooks/SessionHooks";
import { IconHelperWithColors } from "../../../helpers/IconHelper";

const Login = () => {
  document.title = "Stocket - Iniciar Sesión";
  RedirectIfIsAuth();
  const [data, setData] = useState({
    username: "",
    password: "",
  });
  const [loading, setLoading] = useState(false);
  const setTokens = useSesionStore((state) => state.setTokens);
  const navigate = useNavigate();

  const handleChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    await obtenerTokens(data)
      .then((Response) => {
        successMessage("Bienvenido", "Sesión iniciada con éxito");
        setTokens(Response.data);
        navigate("/home");
      })
      .catch((error) => {
        errorMessage(error.response.data);
      })
      .finally(() => {
        setLoading(false);
      });
  };
  return (
    <div>
      <div className="card-header">
        <h3 className="card-title">Iniciar Sesión - Stocket</h3>
      </div>
      <div className="card-body">
        <h5>Ingrese sus credenciales para empezar</h5>

        {loading ? (
          <>
            <Loading />
          </>
        ) : (
          <>
            <div className="row">
              <IconHelperWithColors
                url={"https://cdn.lordicon.com/ppsqwkvn.json"}
                colors={"primary:#9cc2f4,secondary:#3080e8"}
              />
              <div className="col">
                <form className="form-horizontal" onSubmit={handleSubmit}>
                  <div className="card-body">
                    <div className="form-group">
                      {/*Usuario */}
                      <label htmlFor="Username">
                        Usuario <i className="ri-account-box-line"></i>
                      </label>
                      <input
                        type="text"
                        className="form-control form-control-border border-width-2"
                        id="Username"
                        placeholder="Ingrese su usuario. Ej: pepe.perez"
                        name="username"
                        onChange={handleChange}
                        required
                      />
                    </div>
                    {/*Contraseña */}
                    <div className="form-group">
                      <label htmlFor="Password">
                        Contraseña <i className="ri-lock-password-line"></i>
                      </label>
                      <input
                        type="password"
                        className="form-control form-control-border border-width-2"
                        id="Password"
                        placeholder="Ingrese su contraseña"
                        name="password"
                        onChange={handleChange}
                        required
                      />
                    </div>
                  </div>
                  <div className="container">
                    <div className="btn-group">
                      <button type="submit" className="btn btn-success">
                        Entrar <i className="ri-login-box-line"></i>
                      </button>
                      <Link to={`/forgot-password`} className="btn btn-default">
                        ¿Olvidó su contraseña?{" "}
                        <i className="ri-question-line"></i>
                      </Link>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default Login;
