// ui/src/views/Auth/components/RegisterComponent.vue
<template>
  <h5 class="card-title">Registro de usuario</h5>
  <p class="card-text"> Ingrese los datos solicitados </p>
  <div v-if="loading">
    <p>Espere mientras se ejecutan algunas tareas</p>
    <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75" aria-valuemin="0"
        aria-valuemax="100" v-if="loading">
        <div class="progress-bar progress-bar-striped progress-bar-animated" :style="{ width: progress + '%' }"></div>
    </div>
  </div>
  <form @submit.prevent="register" v-else>
    <div class="input-group mb-3">
      <span class="input-group-text" id="inputUsername"><i class="bi bi-person-circle"></i></span>
      <input
        type="text"
        class="form-control"
        placeholder="Indique un nombre de usuario"
        aria-describedby="inputUsername"
        v-model="username"
        required
      />
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text" id="inputPassword"><i class="bi bi-key"></i></span>
      <input
        type="password"
        class="form-control"
        placeholder="Defina una contraseña"
        aria-describedby="inputPassword"
        v-model="password"
        required
      />
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text" id="inputRePassword"><i class="bi bi-key-fill"></i></span>
      <input
        type="password"
        class="form-control"
        placeholder="Vuelva a ingresar la contraseña"
        aria-describedby="inputRePassword"
        required
        v-model="re_password"
      />
    </div>
    <div v-if="password != re_password">
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>¡Error!</strong> Las contraseña no coinciden. Por favor, vuelva a intentarlo.
      </div>
    </div>
    <div class="input-group mb-3">
      <span class="input-group-text" id="inputEmail"><i class="bi bi-envelope"></i></span>
      <input
        type="email"
        class="form-control"
        placeholder="Especifique un correo"
        aria-label="Username"
        aria-describedby="inputEmail"
        required
        v-model="email"
      />
    </div>
    <button type="submit" class="btn btn-success">Crear usuario</button>
  </form>
</template>

<script setup lang="ts">
import {ref} from 'vue'
import { storeUser } from '../services/auth.apis';
import Swal from 'sweetalert2';
import { errorValidator } from '@/hooks/errors.hooks';

const username = ref<string>('')
const password = ref<string>('')
const re_password = ref<string>('')
const email = ref<string>('')
const loading = ref<boolean>(false)
const progress = ref<number>(0)

const register = async() =>{
  loading.value = true
  progress.value = 25
  const data = {
    username: username.value,
    password: password.value,
    re_password: re_password.value,
    email: email.value
  }
  progress.value = 50
  await storeUser(data)
  .then((Response)=>{
    Swal.fire({
      icon: 'success',
      title: 'Usuario creado con éxito',
      text:'Siga las instrucciones enviadas a su correo para activar su cuenta',
      showConfirmButton: true
    })
  })
  .catch((error)=>{
    progress.value = 75
    const reciever = errorValidator(error.response.data);
    Swal.fire({
      icon: 'error',
      title: 'Oops...',
      text: reciever,
      showConfirmButton:false,
      timer: 2500
    })
  })
  .finally(()=>{
    loading.value = false 
    progress.value = 100
  })
}
</script>

// client/src/views/Auth/components/Register.jsx
import { useEffect, useState } from "react";
import Loading from "../../../components/Loading";
import { guardarUsuario } from "../services/auth.apis";
import { errorMessage, successMessage } from "../../../components/messages";
import { useNavigate } from "react-router-dom";
import { IconHelperWithColors } from "../../../helpers/IconHelper";
import { RedirectIfIsAuth } from "../../../hooks/SessionHooks";

const Register = () => {
  document.title = "Stocket - Registrar usuario";
  RedirectIfIsAuth();
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState(false);
  const [data, setData] = useState({
    username: "",
    password: "",
    re_password: "",
    email: "",
  });

  const navigate = useNavigate();

  useEffect(() => {
    if (data.password !== data.re_password) {
      setStatus(true);
    } else {
      setStatus(false);
    }
  }, [data, setStatus]);
  const handleChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
  };
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    await guardarUsuario(data)
      .then((Response) => {
        successMessage(
          "Usuario registrado",
          "Se ha registrado el usuario con éxito. Verifique su correo electrónico para activar su cuenta."
        );
        navigate("/login");
      })
      .catch((error) => {
        errorMessage(error.response.data);
      })
      .finally(() => {
        setLoading(false);
      });
    console.log(data);
  };
  return (
    <div>
      <div>
        <div className="card-header">
          <h3 className="card-title">Registrar usuario - Stocket</h3>
        </div>
        <div className="card-body">
          {loading ? (
            <>
              <Loading />
            </>
          ) : (
            <>
              <h5>Ingrese los datos requeridos</h5>

              <div className="row">
                <IconHelperWithColors
                  url={"https://cdn.lordicon.com/bgebyztw.json"}
                  colors={"primary:#66a1ee,secondary:#2516c7"}
                />
                <div className="col">
                  <form className="form-horizontal" onSubmit={handleSubmit}>
                    <div className="card-body">
                      <div className="form-group">
                        {/*Usuario */}
                        <label htmlFor="Username">
                          Usuario <i className="ri-account-box-line"></i>
                        </label>
                        <input
                          type="text"
                          className="form-control form-control-border border-width-2"
                          id="Username"
                          placeholder="Ingrese su usuario. Ej: pepe.perez"
                          name="username"
                          required
                          onChange={handleChange}
                        />
                      </div>
                      {/*Contraseña */}
                      <div className="form-group">
                        <label htmlFor="Password">
                          Contraseña <i className="ri-lock-password-line"></i>
                        </label>
                        <input
                          type="password"
                          className="form-control form-control-border border-width-2"
                          id="Password"
                          placeholder="Ingrese su contraseña"
                          name="password"
                          required
                          onChange={handleChange}
                        />
                      </div>
                      {/*Repita contraseña */}
                      <div className="form-group">
                        <label htmlFor="RePassword">
                          repita su contraseña{" "}
                          <i className="ri-lock-password-line"></i>
                        </label>
                        <input
                          type="password"
                          className="form-control form-control-border border-width-2"
                          id="RePassword"
                          placeholder="Ingrese su contraseña"
                          name="re_password"
                          required
                          onChange={handleChange}
                        />
                      </div>
                      {status ? (
                        <>
                          <div className="alert alert-danger alert-dismissible">
                            Las contraseñas no coinciden.
                          </div>
                        </>
                      ) : null}
                      {/*email */}
                      <div className="form-group">
                        <label htmlFor="Password">
                          Correo electrónico{" "}
                          <i className="ri-mail-send-fill"></i>
                        </label>
                        <input
                          type="email"
                          className="form-control form-control-border border-width-2"
                          id="Password"
                          placeholder="Ingrese su contraseña"
                          name="email"
                          onChange={handleChange}
                          required
                        />
                      </div>
                    </div>
                    <button type="submit" className="btn btn-success">
                      Registrarse <i className="ri-login-box-line"></i>
                    </button>
                  </form>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default Register;
