// client/src/views/Auth/components/Register.jsx
import { useEffect, useState } from "react";
import Loading from "../../../components/Loading";
import { guardarUsuario } from "../services/auth.apis";
import { errorMessage, successMessage } from "../../../components/messages";
import { useNavigate } from "react-router-dom";
import { IconHelperWithColors } from "../../../helpers/IconHelper";
const Register = () => {
  document.title = "Stocket - Registrar usuario";
  const [loading, setLoading] = useState(false);
  const [status, setStatus] = useState(false);
  const [data, setData] = useState({
    username: "",
    password: "",
    re_password: "",
    email: "",
  });

  const navigate = useNavigate();

  useEffect(() => {
    if (data.password !== data.re_password) {
      setStatus(true);
    } else {
      setStatus(false);
    }
  }, [data, setStatus]);
  const handleChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
  };
  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    await guardarUsuario(data)
      .then((Response) => {
        successMessage(
          "Usuario registrado",
          "Se ha registrado el usuario con éxito. Verifique su correo electrónico para activar su cuenta."
        );
        navigate("/login");
      })
      .catch((error) => {
        errorMessage(error.response.data);
      })
      .finally(() => {
        setLoading(false);
      });
    console.log(data);
  };
  return (
    <div>
      <div>
        <div className="card-header">
          <h3 className="card-title">Registrar usuario - Stocket</h3>
        </div>
        <div className="card-body">
          {loading ? (
            <>
              <Loading />
            </>
          ) : (
            <>
              <h5>Ingrese los datos requeridos</h5>

              <div className="row">
                <IconHelperWithColors
                  url={"https://cdn.lordicon.com/bgebyztw.json"}
                  colors={"primary:#66a1ee,secondary:#2516c7"}
                />
                <div className="col">
                  <form className="form-horizontal" onSubmit={handleSubmit}>
                    <div className="card-body">
                      <div className="form-group">
                        {/*Usuario */}
                        <label htmlFor="Username">
                          Usuario <i className="ri-account-box-line"></i>
                        </label>
                        <input
                          type="text"
                          className="form-control form-control-border border-width-2"
                          id="Username"
                          placeholder="Ingrese su usuario. Ej: pepe.perez"
                          name="username"
                          required
                          onChange={handleChange}
                        />
                      </div>
                      {/*Contraseña */}
                      <div className="form-group">
                        <label htmlFor="Password">
                          Contraseña <i className="ri-lock-password-line"></i>
                        </label>
                        <input
                          type="password"
                          className="form-control form-control-border border-width-2"
                          id="Password"
                          placeholder="Ingrese su contraseña"
                          name="password"
                          required
                          onChange={handleChange}
                        />
                      </div>
                      {/*Repita contraseña */}
                      <div className="form-group">
                        <label htmlFor="RePassword">
                          repita su contraseña{" "}
                          <i className="ri-lock-password-line"></i>
                        </label>
                        <input
                          type="password"
                          className="form-control form-control-border border-width-2"
                          id="RePassword"
                          placeholder="Ingrese su contraseña"
                          name="re_password"
                          required
                          onChange={handleChange}
                        />
                      </div>
                      {status ? (
                        <>
                          <div className="alert alert-danger alert-dismissible">
                            Las contraseñas no coinciden.
                          </div>
                        </>
                      ) : null}
                      {/*email */}
                      <div className="form-group">
                        <label htmlFor="Password">
                          Correo electrónico{" "}
                          <i className="ri-mail-send-fill"></i>
                        </label>
                        <input
                          type="email"
                          className="form-control form-control-border border-width-2"
                          id="Password"
                          placeholder="Ingrese su contraseña"
                          name="email"
                          onChange={handleChange}
                          required
                        />
                      </div>
                    </div>
                    <button type="submit" className="btn btn-success">
                      Registrarse <i className="ri-login-box-line"></i>
                    </button>
                  </form>
                </div>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default Register;

// client/src/views/Auth/components/Register.vue
<script setup lang="ts">
import Animations from '@/components/Animations.vue';
import EditDocument from '@/assets/Icons/EditDocument.json'
import { ref, watchEffect } from 'vue'
import type { Register } from '../services/auth.interfaces';
import useSesionStore from '@/stores/sesion.store';
import { RedirectIfAuth } from '@/middleware/auth.middleware'
document.title = 'Registro de usuarios - Stocket'
RedirectIfAuth()
const loading = ref(false)
const sesion = useSesionStore()
const data = ref({} as Register)

watchEffect(() => {
    loading.value = sesion.loadingStatus
})

const handleChange = (e: any) => {
    data.value = {
        ...data.value,
        [e.target.name]: e.target.value
    }
}

const handleSubmit = async (e: any) => {
    e.preventDefault()
    sesion.registrarUsuario(data.value)
}

</script>

<template>
    <div class="card-header">
        <h6>Registro de usuarios</h6>
    </div>
    <div class="card-body">
        <div class="row">
            <Animations :animation-data="EditDocument" :style="{
                width: '100px',
                height: '100px'
            }" />
            <div class="col">
                <h5>Ingrese sus datos para empezar</h5>
                <form @submit="handleSubmit">
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="bi bi-person-circle"></i></span>
                        <div class="form-floating">
                            <input type="text" name="username" required @input="handleChange" class="form-control"
                                id="Username" placeholder="Username">
                            <label for="Username">Nombre de usuario</label>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                        <div class="form-floating">
                            <input type="password" name="password" @input="handleChange" required class="form-control"
                                id="Password" placeholder="Username">
                            <label for="Password">Ingrese su contraseña</label>
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
                        <div class="form-floating">
                            <input type="password" name="re_password" required @input="handleChange" class="form-control"
                                id="RePassword" placeholder="Username">
                            <label for="RePassword">Repita contraseña</label>
                        </div>
                    </div>
                    <div v-if="data.password !== data.re_password">
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            <strong>¡Error! </strong> Las contraseñas no coinciden
                        </div>
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text"><i class="bi bi-envelope-at"></i></span>
                        <div class="form-floating">
                            <input type="email" name="email" required @input="handleChange" class="form-control" id="Email"
                                placeholder="Username">
                            <label for="Email">Ingrese correo electrónico</label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-success">Guardar <i class="bi bi-save"></i></button>
                </form>
            </div>
        </div>
    </div>
</template>
