// client/src/views/Auth/components/Login.vue
<script setup lang="ts">
import Animations from '@/components/Animations.vue';
import Fingerprint from '@/assets/Icons/Fingerprint.json'
import useSesionStore from '@/stores/sesion.store';
import { ref } from 'vue'
import type { Login } from '../services/auth.interfaces';

document.title = 'Iniciar sesión - Stocket'


const sesion = useSesionStore()

const data = ref({} as Login)

const handleChange = (e: any) => {
  data.value = {
    ...data.value,
    [e.target.name]: e.target.value
  }
}

const handleSubmit = (e: any) => {
  e.preventDefault()
  sesion.iniciarSesion(data.value)
}
</script>
<template>
  <div class="card-header">
    <h6>Inicar sesión</h6>
  </div>
  <div class="card-body">
    <div class="row">
      <Animations :animation-data="Fingerprint" :style="{
        width: '100px',
        height: '100px'
      }" />
      <div class="col">
        <div class="card-title">
          <h5>Iniciar sesión</h5>
        </div>
        <p class="card-text">Ingrese sus credenciales para empezar</p>
        <form @submit="handleSubmit">
          <div class="input-group mb-3">
            <span class="input-group-text"><i class="bi bi-person-badge"></i></span>
            <div class="form-floating">
              <input type="text" name="username" @input="handleChange" class="form-control" id="Username"
                placeholder="Username">
              <label for="Username">Usuario</label>
            </div>
          </div>
          <div class="input-group mb-3">
            <span class="input-group-text"><i class="bi bi-key-fill"></i></span>
            <div class="form-floating">
              <input type="password" name="password" @input="handleChange" class="form-control" id="Password"
                placeholder="Username">
              <label for="Password">Contraseña</label>
            </div>
          </div>
          <div class="btn-group">
            <button type="submit" class="btn btn-success">Entrar <i class="bi bi-arrow-right"></i></button>
            <button type="button" class="btn btn-secondary">¿Olvidó su contraseña?<i class="bi bi-question"></i>
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

// client/src/apps/Auth/components/Login.jsx
import {useState} from 'react'
import {obtenerTokens} from "../services/auth.apis.js";
import sesionStore from "../../../store/sesion.store.js";
import {errorMessage, successMessage} from "../../../components/messages.js";

const Login = () => {
    document.title = 'Login - Stocket'
    const [data, setData] = useState({
        username: '',
        password: ''
    });

    const setTokens = sesionStore((state) => state.setTokens)
    const handleChange = (e) => {
        setData({...data, [e.target.name]: e.target.value})
    }

    const handleSubmit = async (e) => {
        e.preventDefault()
        await obtenerTokens(data)
            .then((Response) => {
                setTokens(Response.data)
                successMessage('¡Hecho!', 'Sesión iniciada correctamente.')
            })
            .catch((error) => {
                errorMessage(error.response.data)
            })
    }
    return (
        <>
            <div className="card-header">Iniciar sesión</div>
            <div className="card-body">
                <div className="card-title h4">
                    Ingrese sus credenciales para iniciar sesión
                </div>
                <form onSubmit={handleSubmit}>
                    <div className="input-group mb-3">
                        <span className="input-group-text"><i className="bi bi-person-badge"></i></span>
                        <div className="form-floating">
                            <input type="text" className="form-control" name="username" id="floatingInputGroupUsername"
                                   placeholder="Username" required onChange={handleChange}/>
                            <label htmlFor="floatingInputGroupUsername">Usuario</label>
                        </div>
                    </div>
                    <div className="input-group mb-3">
                        <span className="input-group-text"><i className="bi bi-key"></i></span>
                        <div className="form-floating">
                            <input type="password" className="form-control" id="floatingInputGroupPassword"
                                   placeholder="Contraseña" name="password" onChange={handleChange} required/>
                            <label htmlFor="floatingInputGroupPassword">Contraseña</label>
                        </div>
                    </div>
                    <button type="submit" className="btn btn-success">Entrar <i className="bi bi-door-open"></i>
                    </button>
                    <p className="text-muted">¿Olvidó su contraseña?</p>
                </form>
            </div>
        </>
    )
}

export default Login
