// client/src/views/Empresa/components/Home.jsx
import useSesionStore from "../../../store/sesion.store";
import { IconHelperWitoutColors } from "../../../helpers/IconHelper";
import { Link } from "react-router-dom";

const Home = () => {
  const { empresaData } = useSesionStore.getState();

  return (
    <div>
      <div className="card-header">
        <h3 className="card-title">Datos de empresa</h3>
        <div className="card-tools">
          {empresaData && empresaData.length ? (
            <Link to={`/empresa/update`} className="btn btn-warning">
              Editar <i className="ri-edit-line"></i>
            </Link>
          ) : (
            <button className="btn btn-success">Añadir </button>
          )}
        </div>
      </div>
      <div className="card-body">
        <div className="row">
          {empresaData && empresaData.length ? (
            <IconHelperWitoutColors
              url={"https://cdn.lordicon.com/teydnehw.json"}
            />
          ) : (
            <IconHelperWitoutColors
              url={"https://cdn.lordicon.com/jxzkkoed.json"}
            />
          )}
          <div className="col">
            {empresaData && empresaData.length ? (
              <>
                <h3>Razón Social: {empresaData[0]?.name}</h3>
                <div>NIT: {empresaData[0]?.NIT}</div>
                <div>Dirección: {empresaData[0]?.address}</div>
                <div>Teléfono: {empresaData[0]?.phone}</div>
                <div>Correo: {empresaData[0]?.email}</div>
                <div>Web: {empresaData[0]?.web || "No hay datos"}</div>
                <div>
                  Descripción: {empresaData[0]?.description || "No hay datos"}
                </div>
              </>
            ) : (
              <>
                <h3>¡Error!</h3>
                <p>
                  No hay datos para mostrar, añada datos sobre su empresa y
                  vuelva a intentarlo
                </p>
              </>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;

// client/src/views/Empresa/main/Home.vue
<template>
  <div class="card-header">
    <div class=" d-flex align-items-center">
      <div class="text-center flex-grow-1 mb-0">
        <h6>Datos de empresa</h6>
      </div>
      <RouterLink :to="{ name: 'ActualizarEmpresa' }" class="btn btn-warning ml-auto" v-if="empresa.empresaData.NIT">
        Editar <i class="bi bi-pencil-square"></i>
      </RouterLink>
      <RouterLink :to="{ name: 'CrearEmpresa' }" type="button" class="btn btn-success" v-else>Añadir <i
          class="bi bi-plus-square"></i></RouterLink>
    </div>
  </div>
  <div class="card-body">
    <div class="row">
      <Animations :animation-data="Document" :style="{ width: '100px', height: '100px' }"
        v-if="empresa.empresaData.NIT" />
      <Animations :animation-data="Warning" :style="{ width: '100px', height: '100px' }" v-else />
      <div class="col">
        <div class="container" v-if="empresa.empresaData.NIT">
          <h5>Información de la entidad</h5>
          <p>NIT: {{ empresa.empresaData.NIT }}</p>
          <p>Nombre: {{ empresa.empresaData.name }} </p>
          <p>Descripción: {{ empresa.empresaData.description || 'No hay datos' }}</p>
          <p>Correo: {{ empresa.empresaData.email }}</p>
          <p>Teléfono: {{ empresa.empresaData.phone }}</p>
          <p>Dirección: {{ empresa.empresaData.address }}</p>
          <p>Sitio web: {{ empresa.empresaData.web || 'No hay datos' }}</p>
        </div>
        <div v-else>
          <span class="h4">No hay datos que mostrar</span>
          <p>Parece que no hay datos para esta categoría. Añada uno para empezar</p>
        </div>

      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import Document from '@/assets/Icons/Document.json'
import Warning from '@/assets/Icons/Warning.json'
import Animations from '@/components/Animations.vue';
import useEmpresaStore from '@/stores/empresa.store';

const empresa = useEmpresaStore()

document.title = "Empresa - Stocket"
</script>
