// client/src/components/Navbar.jsx
import { Link, useNavigate } from "react-router-dom";
import useSesionStore from "../store/sesion.store";
import { successMessage } from "./messages";

const Navbar = (dateTime) => {
  const { isAuth } = useSesionStore.getState();
  const navigate = useNavigate();
  const cerrarSesion = useSesionStore((state) => state.logout);
  const userData = useSesionStore((state) => state.userData);
  const salir = () => {
    successMessage("Sesión cerrada", "Se ha cerrado la sesión con éxito");
    cerrarSesion();
    navigate("/");
  };
  return (
    <>
      <nav className="navbar navbar-expand navbar-light navbar-white">
        <div className="container">
          <lord-icon
            src="https://cdn.lordicon.com/hnppcsvw.json"
            trigger="hover"
            colors="primary:#4030e8,secondary:#66a1ee"
            style={{ width: "50px", height: "50px" }}
          ></lord-icon>
          <div className="navbar-brand">
            <Link to={"/"} className="brand-text link-dark">
              Stocket
            </Link>
          </div>

          <ul className="navbar-nav">
            {isAuth ? (
              <>
                <li className="nav-item"></li>
                <li className="nav-item d-none d-sm-inline-block">
                  <a href="index3.html" className="nav-link">
                    Home
                  </a>
                </li>
                <li className="nav-item d-none d-sm-inline-block">
                  <a href="#" className="nav-link">
                    Contact
                  </a>
                </li>
                <li className="nav-item dropdown">
                  <a
                    className="nav-link dropdown-toggle"
                    href="#"
                    id="navbarDropdown4"
                    role="button"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                  >
                    Help
                  </a>
                  <div
                    className="dropdown-menu"
                    aria-labelledby="navbarDropdown4"
                  >
                    <a className="dropdown-item" href="#">
                      FAQ
                    </a>
                    <a className="dropdown-item" href="#">
                      Support
                    </a>
                    <div className="dropdown-divider"></div>
                    <a className="dropdown-item" href="#">
                      Contact
                    </a>
                  </div>
                </li>
              </>
            ) : (
              <>
                <li className="nav-item"></li>
                <li className="nav-item"></li>
                <li className="nav-item"></li>
              </>
            )}
          </ul>

          <form
            className="form-inline ml-3"
            style={{
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <div className="input-group input-group-sm">
              <input
                className="form-control form-control-navbar"
                type="search"
                placeholder="Search"
                aria-label="Search"
                value={dateTime.dateTime}
                readOnly
              />
              <div className="input-group-append">
                <div className="btn btn-navbar">
                  <i className="ri-time-line"></i>
                </div>
              </div>
            </div>
          </form>

          <ul className="navbar-nav ml-auto">
            {isAuth ? (
              <>
                <div className="btn-group">
                  <button type="button" className="btn btn-primary">
                    Sesión iniciada como {userData?.username}
                  </button>
                  <button
                    type="button"
                    className="btn btn-default dropdown-toggle dropdown-icon"
                    data-toggle="dropdown"
                  ></button>
                  <div className="dropdown-menu" role="menu">
                    <Link to={`/profile`} className="dropdown-item" href="#">
                      Ver datos de usuario{" "}
                      <i className="ri-account-pin-box-line"></i>
                    </Link>
                    <a className="dropdown-item" href="#">
                      Cambiar Contraseña <i className="ri-key-line"></i>
                    </a>
                    <div className="dropdown-divider"></div>
                    <a className="dropdown-item" onClick={salir}>
                      Salir
                    </a>
                  </div>
                </div>
              </>
            ) : (
              <div className="btn-group nav-item">
                <Link
                  to={"/register"}
                  type="button"
                  className="btn btn-primary"
                >
                  Registrarse <i className="ri-user-add-line"></i>
                </Link>
                <Link to={"/login"} type="button" className="btn btn-secondary">
                  Entrar <i className="ri-login-box-line"></i>
                </Link>
              </div>
            )}
          </ul>
        </div>
      </nav>
    </>
  );
};

export default Navbar;

// client/src/components/Navbar.vue
<template>
    <nav class="py-2 bg-body-tertiary border-bottom">
        <div class="container d-flex flex-wrap nav-item">
            <ul class="nav me-auto">
                <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2 active"
                        aria-current="page">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link link-body-emphasis px-2">About</a></li>
            </ul>
            <ul class="nav" v-if="sesion.isAuth">
                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        sesión iniciada como {{ sesion.userData.username }}
                    </button>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Perfil de usuario <i class="bi bi-person-badge"></i></a></li>
                        <li>
                            <RouterLink :to="{ name: 'ResetPassword' }" class="dropdown-item">Cambiar contraseña <i
                                    class="bi bi-key"></i></RouterLink>
                        </li>
                        <li><a class="dropdown-item" @click="sesion.cerrarSesion">Salir <i class="bi bi-power"></i></a></li>
                    </ul>
                </div>

            </ul>
            <ul class="nav" v-else>
                <li class="nav-item">
                    <RouterLink :to="{ name: 'Login' }" class="nav-link link-body-emphasis px-2">Login</RouterLink>
                </li>
                <li class="nav-item">
                    <RouterLink :to="{ name: 'Register' }" class="nav-link link-body-emphasis px-2">Sign up</RouterLink>
                </li>
            </ul>
        </div>
    </nav>
    <header class="py-3 mb-4 border-bottom">
        <div class="container d-flex flex-wrap justify-content-center">
            <a href="/" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
                <div :style="{
                    display: 'flex',
                    justifyContent: 'center',
                    alignItems: 'center'
                }">
                    <div v-if="sesion.isAuth">
                        <h3>Stocket - {{ sesion.userData.groups.length ?
                            sesion.userData.groups[0] : 'Invitado' }}</h3>
                    </div>
                    <div v-else>
                        <h3>Stocket</h3>
                    </div>
                </div>
            </a>
            <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search">
                <div class="input-group mb-3">
                    <span class="input-group-text" id="input1"><i class="bi bi-watch"></i></span>
                    <input type="text" class="form-control" readonly :value="props.dateTime" />
                </div>
            </form>
        </div>
    </header>
</template>

<script setup lang="ts">
import useSesionStore from '@/stores/sesion.store';
const sesion = useSesionStore()
const props = defineProps<{
    dateTime: string
}>()
</script>
